language: python

python:
  - "3.7"

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install --assume-yes libudev-dev

install:
  - pip3 install homeassistant

script:
  - hass --config . --script check_config

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

