 dist: bionic

language: python

python:
  - "3.7"

git:
  depth: 1
  quiet: true

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install --assume-yes libudev-dev python3.7-dev

install:
  - pip3 install homeassistant

script:
  - hass --config . --script check_config --info all

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

